{% set name = "limits" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f1311b9d48fcccf2b3120dad67126a329f44c5f9a3c33df97d6c19e20e66f82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools

test:
  imports:
    - limits

about:
  home: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Rate limiting utilities
  doc_url: https://limits.readthedocs.io/en/stable/
  dev_url: https://github.com/alisaifee/limits

extra:
  recipe-maintainers:
    - tiefling-cat
