{% set name = "limits" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limits-{{ version }}.tar.gz
  sha256: d4270d29591cc5eceab19be053455a4e619ba395062502bde2b5681af7dc1be8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools

test:
  imports:
    - limits

about:
  home: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Rate limiting utilities
  doc_url: https://limits.readthedocs.io/en/stable/
  dev_url: https://github.com/alisaifee/limits

extra:
  recipe-maintainers:
    - tiefling-cat
    - xylar
