{% set name = "limits" %}
{% set version = "3.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/limits-{{ version }}.tar.gz
  sha256: 28f75bda2cfedbe823aa796581c352e18bdc26a2752a4842c8e92e63b0b22fac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - typing_extensions
    - python >=3.8
    - deprecated >=1.2
    - importlib-resources >=1.3
    - packaging >=21,<25
    - typing-extensions

test:
  imports:
    - limits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://limits.readthedocs.org
  summary: Rate limiting utilities
  dev_url: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://limits.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - tiefling-cat
    - xylar
