{% set name = "limits" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limits-{{ version }}.tar.gz
  sha256: 6e657dccafce64fd8ee023ebf4593cd47e9eac841fd1dec3448f48673ba10b7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - deprecated >=1.2
    - importlib-resources >=1.3
    - packaging >=21,<24
    - typing-extensions

test:
  imports:
    - limits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://limits.readthedocs.org
  summary: Rate limiting utilities
  dev_url: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://limits.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - tiefling-cat
    - xylar
