{% set name = "limits" %}
{% set version = "5.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/limits-{{ version }}.tar.gz
  sha256: b298e4af0b47997da03cbeee9df027ddc2328f8630546125e81083bb56311827

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - deprecated >=1.2
    - packaging >=21,<26
    - typing_extensions

test:
  imports:
    - limits
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://limits.readthedocs.org
  summary: Rate limiting utilities
  dev_url: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://limits.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - tiefling-cat
    - xylar
