{% set name = "limits" %}
{% set version = "3.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/limits-{{ version }}.tar.gz
  sha256: 1ee31d169d498da267a1b72183ae5940afc64b17b4ed4dfd977f6ea5607c2cfb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - deprecated >=1.2
    - importlib-resources >=1.3
    - packaging >=21,<25
    - typing-extensions

test:
  imports:
    - limits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://limits.readthedocs.org
  summary: Rate limiting utilities
  dev_url: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://limits.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - tiefling-cat
    - xylar
